# Generated by Django 6.0.1 on 2026-02-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0003_alter_taskgroup_options_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('due_date', 'name')},
        ),
    ]
